universe = vanilla
MY.WantOS = "el7"
Executable = /afs/cern.ch/user/j/jiahua/CROWN/condor/Job_test_top.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN/condor/Job_test_top.sh, /afs/cern.ch/user/j/jiahua/CROWN/build/bin/vbfhmm_config_all_resubv7_v2_top_2018, /afs/cern.ch/user/j/jiahua/CROWN/build/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_UL18_trigger/TTZToLLNuNu_M-10-amcatnlo_UL20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN/condor/Jobs/TTZToLLNuNu_M-10-amcatnlo_UL20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN/condor/Jobs/TTZToLLNuNu_M-10-amcatnlo_UL20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN/condor/Jobs/TTZToLLNuNu_M-10-amcatnlo_UL20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/40000/FA963E9A-8085-AC47-A98A-22758494F428.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/40000/D3AE2D58-C3EC-A545-B688-D9B98F9C6966.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/40000/4C6BFB3E-92A5-8F45-ACFE-BAED3415B392.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/40000/9937A6A1-574A-CD45-9ADE-2ECDD42C7CEF.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/40000/F890FF6C-1379-5B40-A629-C2D136A38E79.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/40000/8D5CED32-BC07-4446-9DF1-A1E79B30AC78.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/2430000/35747048-3A69-F64E-9CAE-31095041EFA3.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/2430000/FC233DF4-D00C-F34A-B1C9-846EE9D08EC9.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/2430000/4A87BD9C-3796-7943-BC03-3A0A99C82235.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/2430000/C2D49646-2369-EA4A-9138-C953A08848E5.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/2430000/846AFEC1-5148-D947-90DD-4B8709C79554.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/2430000/5D3F140F-FBB9-B140-B7CC-85AA5FD74965.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/2430000/D196466C-C530-7248-8E80-CC8454362A14.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/2430000/4CB20B7E-270A-8541-9786-23B8703D8FCB.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/2430000/A5A5A758-0AF2-5A4F-8BE5-3BE4EE965039.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/2430000/0E134A8D-17DC-B149-9916-1E8DA19E4F9E.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/2430000/2854B58A-88AD-FA47-82C6-0FDBA09F3ECC.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/2430000/8830C5C6-2C2E-E443-AF18-698F6DB4EE23.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/40000/602117A1-A9AD-BE4E-8642-9672BD0DCB5E.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/40000/F4B92240-34BB-9843-9C04-53785AD196C9.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTZToLLNuNu_M-10_TuneCP5_13TeV-amcatnlo-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v1/40000/CD6F2C6C-2E69-0D44-AD61-CE132CD9C346.root
Queue
