universe = vanilla
MY.WantOS = "el7"
Executable = /afs/cern.ch/user/j/jiahua/CROWN/condor/Job_test_dyjets.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN/condor/Job_test_dyjets.sh, /afs/cern.ch/user/j/jiahua/CROWN/build_v7/bin/vbfhmm_config_all_resubv7_v2_dyjets_2018, /afs/cern.ch/user/j/jiahua/CROWN/build_v7/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_UL18_nocut/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM_ULRunIIAutumn18NanoAODv7-Nano02Apr2020_102X_upgrade2018_realistic_v21-v1
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN/condor/Jobs/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM_ULRunIIAutumn18NanoAODv7-Nano02Apr2020_102X_upgrade2018_realistic_v21-v1_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN/condor/Jobs/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM_ULRunIIAutumn18NanoAODv7-Nano02Apr2020_102X_upgrade2018_realistic_v21-v1_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN/condor/Jobs/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM_ULRunIIAutumn18NanoAODv7-Nano02Apr2020_102X_upgrade2018_realistic_v21-v1_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/EE83D064-7B1B-BC4F-882F-9FF60C52E2D0.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/D695BFE9-D2A6-474C-BE9D-96CFF6196C00.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/AE6B8DDF-20DB-4B43-AA6E-A0C84691B0C4.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/8F49BF4A-9588-1B44-86E4-4D2BA3C24F64.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/8AE4D5CB-9968-0744-8CF4-FFE746EEDDA8.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/057C483F-12AF-364D-B5DB-3E28F19E2E99.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/48556852-9CA8-9B46-9A16-2D05889AD722.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/61089A31-0AAB-824B-9987-529BA21CFCDF.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/A5655B7B-3EB6-D943-A5E6-1A21A6F336CF.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/1DEF0A32-15E8-9D4D-BCE4-1A6B56652179.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/BDB837B0-3E31-7A46-A196-F944C05C2AFC.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/DCC707EF-D336-474B-A24C-38C4598BABA5.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/09D12770-280A-354E-A53D-A6186CAF7A7F.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/BE965065-2C51-944C-9C35-1860111DDBC3.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/F07DB21B-31D6-534A-9757-8CCBCDCE2013.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/59849E97-FD9B-3F49-B2D3-0CC75FACE794.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/C1154088-DA3D-9D4F-B7F7-8C37DF246702.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/7701D628-DBCE-FE49-A91E-E4606FDAE0B8.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/60000/347E5576-FADE-4B48-9640-A444C417BA42.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/100000/6810929F-B47A-5842-B550-57FA81BA1373.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/100000/DDF272B1-131C-1248-BA9A-076C19126056.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/100000/59D46CBD-0512-5C4D-9CD6-EC67B173D4B6.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/100000/86A513BE-890E-1A48-BECB-7643757B0789.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/100000/4BF2322E-18EA-914E-9E1B-2516DC64FFDF.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/100000/DC1521EC-D825-3D41-8212-D74D85831CF3.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/100000/77E26CE1-9593-EF41-B78D-9EF3FA95FA9A.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/100000/53A8812F-6DE4-8B49-BE1C-3AE405753657.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIIAutumn18NanoAODv7/DYJetsToLL_M-105To160_TuneCP5_PSweights_13TeV-madgraphMLM-pythia8/NANOAODSIM/Nano02Apr2020_102X_upgrade2018_realistic_v21-v1/100000/1787626E-1A7E-1447-9752-91DB94C0DB4C.root
Queue
