universe = vanilla
MY.WantOS = "el7"
Executable = /afs/cern.ch/user/j/jiahua/CROWN/condor/Job_test_top.sh
should_transfer_files = YES
Transfer_Input_Files = /afs/cern.ch/user/j/jiahua/CROWN/condor/Job_test_top.sh, /afs/cern.ch/user/j/jiahua/CROWN/build/bin/vbfhmm_config_all_resubv7_v2_top_2018, /afs/cern.ch/user/j/jiahua/CROWN/build/libCROWNLIB.so
Proxy_path = /afs/cern.ch/user/j/jiahua/proxy/x509up_u139833
output_path = /eos/user/j/jiahua/MC_UL18_trigger/TTTW-madgraph_UL20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2
arguments = $(Proxy_path) $(output_path) $(input_name) $(ClusterID) $(ProcId)
Output = /afs/cern.ch/user/j/jiahua/CROWN/condor/Jobs/TTTW-madgraph_UL20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2_$(ClusterId)_$(ProcId).out
Error = /afs/cern.ch/user/j/jiahua/CROWN/condor/Jobs/TTTW-madgraph_UL20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2_$(ClusterId)_$(ProcId).err
Log = /afs/cern.ch/user/j/jiahua/CROWN/condor/Jobs/TTTW-madgraph_UL20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v2_$(ClusterId)_$(ProcId).log
request_cpus = 1
+JobFlavour = "workday"
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTTW_TuneCP5_13TeV-madgraph-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v2/260000/ECACC29E-698C-EE42-A460-BAD444727AFA.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTTW_TuneCP5_13TeV-madgraph-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v2/2530000/07E85166-4C72-3B4E-9572-2D070F2EF385.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTTW_TuneCP5_13TeV-madgraph-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v2/260000/07350478-4397-054C-B6F8-9F6979FF7357.root
Queue
input_name = root://cms-xrd-global.cern.ch//store/mc/RunIISummer20UL18NanoAODv9/TTTW_TuneCP5_13TeV-madgraph-pythia8/NANOAODSIM/106X_upgrade2018_realistic_v16_L1v1-v2/2520000/9660E5EF-E305-7546-B26E-9A759DBC1976.root
Queue
